### ISSUE TITLE
Trip POST request is not working

### ISSUE THREAD

**Issue by SamehNagi** [SamehNagi/ShipLe#10]
Using the Trip POST request to post the following is not working:
    {
        "UserID": 7,
        "SourceCountry": 5,
        "DestinationCountry": 3,
        "TransportationType": 1,
        "TravelDate": "2019-01-03T00:00:00",
        "ArrivalDate": "2019-05-03T00:00:00",
        "AvailableWeight": 05,
        "TripNote": "I don't take electronics!"
    }
This exception arise: 
MySql.Data.MySqlClient.MySqlException: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 't take electronics!')' at line 1'

**Comment by AhZidan** [comment]
This is due to using the single quote character ' in the TripNote Field.
The solution is parameterize statement but we are facing a problem to use parameters in Insert statements. the feature is not working probably with MySQL driver.

also the above entry is not valid, for example the date formate is not correct.
