### ISSUE TITLE
Shipment PUT request is not working

### ISSUE THREAD

**Issue by SamehNagi** [SamehNagi/ShipLe#12]
Using the Shipment PUT request to modify the following is not working:
{
    "TripID": 2,
    "UserID": 2,
    "SourceCountry": 2,
    "DestinationCountry": 1,
    "DeliveryDate": "2019-05-01T00:00:00",
    "ShipmentName": "Docs",
    "ShipmentNote": "Important!"
}
This exception arise:
MySql.Data.MySqlClient.MySqlException: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Where ShipmentID    = '2'' at line 1'

**Comment by AhZidan** [comment]
This is obviously due to that
1- Use of single quote characters with ShipmentID field while it is a numeric field.
2- Use two of the single quot in the statement.
3- This seems an old version as all SQL statements are parameterized except for insert statements.

Finally, 
This feature is tested and was found working fine.
